# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Black Duck Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.9.0

      ### Use below configuration to set specific detect environment variables
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.base_ref }}
        DETECT_DETECTOR_SEARCH_CONTINUE: true
        DETECT_DETECTOR_SEARCH_DEPTH: 10
      with:
        blackduck_url: ${{ vars.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackduck_scan_full: true
        blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'

      ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
      # blackduck_fixpr_enabled: true
      # blackduck_fixpr_maxCount: 5
      # blackduck_fixpr_filter_severities: 'CRITICAL,HIGH'
      # blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
      # github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'

      ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
      # blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
      # blackduck_reports_sarif_file_path: '/Users/tmp/report.sarif.json' # File path including file name where SARIF report should be created(need to include file name as well)
      # blackduck_reports_sarif_severities: 'CRITICAL,HIGH'
      # blackduck_reports_sarif_groupSCAIssues: true # By default true
      # blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
      # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true

      ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
      # include_diagnostics: true

    - name: Black Duck PR Scan
      uses: synopsys-sig/synopsys-action@v1.9.0
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.base_ref }}
        DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
        DETECT_DETECTOR_SEARCH_CONTINUE: true
        DETECT_DETECTOR_SEARCH_DEPTH: 10
      with:
        blackduck_url: ${{ vars.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackduck_scan_full: false  
        blackduck_prComment_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        